version: '3.7'
services:
  mysql:
    image: 'mysql:8'
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: cartoesvr
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './database:/var/lib/mysql'
  application:
    container_name: api-autorizador
    build: ../cartoes-vr
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cartoesvr?autoReconnect=true&useSSL=false
    ports:
      - '8080:8080'
    volumes:
      - './app:/app'
    depends_on:
      - mysql
